header:
  license:
    spdx-id: BSD-3-Clause
    copyright-owner: UChicago Argonne, LLC
    content: |
      Copyright 2019 UChicago Argonne, LLC.
      (c.f. AUTHORS, LICENSE)

      This file is part of the libnrm project.
      For more info, see https://github.com/anlsys/libnrm

      SPDX-License-Identifier: BSD-3-Clause

  paths:
    - '**/*.c'
    - '**/*.h'
    - '**/*.h.in'
  paths-ignore:
    - '**/*.f90'
    - '**/nrmf.h'
  comment: never
