name: builds
on:
  push:
    branches:
      - master
  pull_request:

env:
  VERBOSE: 1
jobs:
  generic:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y gcc make autoconf automake libtool pkg-config libzmq3-dev libzmq5 libczmq-dev libczmq4 libprotobuf-c-dev protobuf-c-compiler libjansson-dev libjansson4 check libhwloc-dev bats libpapi-dev
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: configure
        run: |
          ./autogen.sh
          mkdir build
          ./configure --prefix=`pwd`/build
      - run: make
      - run: make check
      - run: make install
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: generic
          path: |
            config.log
            *.log
  out-of-tree:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y gcc make autoconf automake libtool pkg-config libzmq3-dev libzmq5 libczmq-dev libczmq4 libprotobuf-c-dev protobuf-c-compiler libjansson-dev libjansson4 check libhwloc-dev bats libpapi-dev
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: configure
        run: |
          ./autogen.sh
          mkdir out
          cd out
          mkdir build
          ../configure --prefix=`pwd`/build
      - run: make
        working-directory: out
      - run: make check
        working-directory: out
      - run: make install
        working-directory: out
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: out-of-tree
          path: |
            out/config.log
            out/*.log
  valgrind:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y gcc make autoconf automake libtool pkg-config libzmq3-dev libzmq5 libczmq-dev libczmq4 libprotobuf-c-dev protobuf-c-compiler libjansson-dev libjansson4 check libhwloc-dev valgrind bats libpapi-dev
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: configure
        run: |
          ./autogen.sh
          mkdir build
          ./configure --prefix=`pwd`/build --enable-valgrind
      - run: make
      - run: make check-valgrind
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: valgrind
          path: |
            config.log
            *.log
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-20.09
      - run: nix-build -A libnrm
  distcheck:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y gcc make autoconf automake libtool pkg-config libzmq3-dev libzmq5 libczmq-dev libczmq4 libprotobuf-c-dev protobuf-c-compiler libjansson-dev libjansson4 check libhwloc-dev bats libpapi-dev
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: configure
        run: |
          ./autogen.sh
          mkdir build
          ./configure --prefix=`pwd`/build
      - run: make
      - run: make distcheck
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: distcheck
          path: |
            config.log
