name: style-checks
on: [pull_request]
jobs:
  clang-format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: retrieve merge target info
        run: git fetch origin $GITHUB_BASE_REF
      - run: sudo apt-get update
      - run: sudo apt-get install -y clang-format-10
      - name: run git-clang-format
        run: |
          target=$(git rev-parse origin/$GITHUB_BASE_REF)
          git-clang-format-10 --quiet --diff $target > clang-format-diff
          lint=$(grep -v --color=never "no modified files to format" clang-format-diff || true)
          if [ ! -z "$lint" ]; then echo "format errors, inspect the clang-format-diff artifact for info"; exit 1; else exit 0; fi
        shell: bash
      - name: output clang format diff
        if: always()
        run: cat ./clang-format-diff
  license-check:
    runs-on: ubuntu-latest
    container: apache/skywalking-eyes
    steps:
      - uses: actions/checkout@v4
      - run: /bin/license-eye -c .licenserc.yml -v debug header check
  python-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install flake8 black
      - run: flake8
      - run: black -l 79 --check bindings/python
  doc-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-23.05
      - run: nix-shell --command "./autogen.sh; ./configure --enable-docs; make html"
